// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDKe4_LBtQI48aX2GLydSBTe3z8uE9YtaA',
    appId: '1:1087981533992:web:7d43acb329c73cabee2e1d',
    messagingSenderId: '1087981533992',
    projectId: 'bootacmpmaterial',
    authDomain: 'bootacmpmaterial.firebaseapp.com',
    storageBucket: 'bootacmpmaterial.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCr3vDDZ_CI7OZ3G6ZYNcxBJjznUGvYeCk',
    appId: '1:1087981533992:android:1597ed1300eb365fee2e1d',
    messagingSenderId: '1087981533992',
    projectId: 'bootacmpmaterial',
    storageBucket: 'bootacmpmaterial.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDCnZjyqbF2xznzZYu9bw1_2eNXvPq5YcU',
    appId: '1:1087981533992:ios:dd77c77da2c0cdefee2e1d',
    messagingSenderId: '1087981533992',
    projectId: 'bootacmpmaterial',
    storageBucket: 'bootacmpmaterial.appspot.com',
    iosClientId:
        '1087981533992-18vf5jhn76inibj4rmagpvvhe3o11aj3.apps.googleusercontent.com',
    iosBundleId: 'com.example.reqApiApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDCnZjyqbF2xznzZYu9bw1_2eNXvPq5YcU',
    appId: '1:1087981533992:ios:dd77c77da2c0cdefee2e1d',
    messagingSenderId: '1087981533992',
    projectId: 'bootacmpmaterial',
    storageBucket: 'bootacmpmaterial.appspot.com',
    iosClientId:
        '1087981533992-18vf5jhn76inibj4rmagpvvhe3o11aj3.apps.googleusercontent.com',
    iosBundleId: 'com.example.reqApiApp',
  );
}
